// apps/web-vue/src/pages/reset-password.vue
<template>
    <AuthLayout>
        <div class="card max-w-md w-full shadow-xl">
            <div class="card-body">
                <h2 class="text-center font-extrabold mb-3">Reset your password</h2>
                <p class="text-center">
                    An OTP is sent to your email <code>{{ email }}</code>. Enter the OTP to reset your
                    password
                </p>
                <form @submit.prevent="handleResetPassword">
                    <div class="form-control w-full">
                        <label class="label">
                            <span class="label-text">OTP</span>
                        </label>
                        <input min="100000" max="999999" type="number" placeholder="000000" autocomplete="off"
                            class="input input-bordered w-full" v-model="otp" />
                    </div>
                    <div class="form-control w-full">
                        <label class="label">
                            <span class="label-text">New Password</span>
                        </label>
                        <input type="password" placeholder="*********" autocomplete="new-password"
                            class="input input-bordered w-full" v-model="password" />
                    </div>
                    <div class="text-center">
                        <button type="submit" class="btn variant-filled mt-4 w-full" :class="submitting ? 'loading' : ''"
                            :disabled="submitting">
                            Update Password </button>
                    </div>
                </form>
                <p class="text-center mt-2">
                    <RouterLink to="/login">Back to login ></RouterLink>
                </p>
            </div>
        </div>
    </AuthLayout>
</template>
<script setup lang="ts">
import AuthLayout from '@/layouts/AuthLayout.vue'
import { ref } from 'vue';

let email: string

const otp = ref('')
const password = ref('')
const submitting = ref(false)


const handleResetPassword = () => {

}
</script>

// apps/web-sveltekit/src/routes/(guest)/auth/reset-password/+page.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { client, getMessageFromError } from '$lib/trpc/client';
	import { Toast, toastStore } from '@skeletonlabs/skeleton';
	import { onMount } from 'svelte';

	let otp: number;
	let password = '';
	let email: string;
	let submitting = false;

	onMount(() => {
		const email_ = sessionStorage.getItem('forgot_password_email');

		if (!email_) {
			return goto('/auth/register');
		}

		email = email_;
		sessionStorage.setItem('no_of_email_sent', String(1));
	});

	const handleResetPassword = async () => {
		try {
			submitting = true;

			const { message } = await client().auth.resetPassword.mutate({
				email: email,
				otp,
				password
			});

			sessionStorage.clear();

			toastStore.trigger({
				message,
				autohide: true,
				background: 'variant-filled-success'
			});

			toastStore.trigger({
				message: 'Redirecting to login',
				autohide: true,
				background: 'variant-filled-success'
			});

			setTimeout(() => {
				goto('/auth/login');
			}, 1000);
		} catch (err) {
			const message = getMessageFromError(err);
			toastStore.trigger({
				message,
				autohide: true,
				background: 'variant-filled-error'
			});
		} finally {
			submitting = false;
		}
	};
</script>

<svelte:head>
	<title>Telecord</title>
</svelte:head>
<Toast />
<div class="card px-4 py-8 max-w-md w-full">
	<h2 class="text-center font-extrabold mb-3">Reset your password</h2>
	<p>
		An OTP is sent to your email <code>{email}</code>. Enter the OTP to reset your password
	</p>
	<form on:submit|preventDefault={handleResetPassword}>
		<label class="label mt-2">
			<span>Enter your OTP</span>
			<input
				class="input"
				type="number"
				placeholder="000000"
				autocomplete="off"
				bind:value={otp}
				min="100000"
				max="999999"
			/>
		</label>
		<label class="label mt-2">
			<span>Enter new password</span>
			<input
				class="input"
				type="password"
				placeholder="********"
				autocomplete="new-password"
				bind:value={password}
			/>
		</label>
		<button type="submit" class="btn variant-filled mt-4 w-full" disabled={submitting}
			>{submitting ? 'Please wait...' : 'Reset Password'}</button
		>
	</form>
	<p class="text-center mt-2">
		<a href="/auth/login">Back to login?</a>
	</p>
</div>
