// apps/web-sveltekit/src/routes/(guest)/auth/forgot-password/+page.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { client, getMessageFromError } from '$lib/trpc/client';
	import { Toast, toastStore } from '@skeletonlabs/skeleton';

	let email = '';
	let submitting = false;

	const handleForgotPassword = async () => {
		try {
			submitting = true;

			const { message } = await client().auth.forgotPassword.mutate({
				email
			});

			sessionStorage.setItem('forgot_password_email', email);
			goto('/auth/reset-password');
		} catch (err) {
			const message = getMessageFromError(err);
			toastStore.trigger({
				message,
				autohide: true,
				background: 'variant-filled-error'
			});
		} finally {
			submitting = false;
		}
	};
</script>

<svelte:head>
	<title>Telecord</title>
</svelte:head>
<Toast />
<div class="card px-4 py-8 max-w-md w-full">
	<h2 class="text-center font-extrabold mb-3">Forgot your password?</h2>
	<p>Don't worry! Reset your password in few clicks</p>
	<form on:submit|preventDefault={handleForgotPassword}>
		<label class="label mt-2">
			<span>Enter your email</span>
			<input
				class="input"
				type="email"
				placeholder="john@example.com"
				autocomplete="email"
				bind:value={email}
			/>
		</label>
		<button type="submit" class="btn variant-filled mt-4 w-full" disabled={submitting}
			>{submitting ? 'Please wait...' : 'Continue'}</button
		>
	</form>
	<p class="text-center mt-2">
		<a href="/auth/login">Back to login?</a>
	</p>
</div>

// apps/web-vue/src/pages/forgot-password.vue
<template>
    <AuthLayout>
        <div class="card max-w-md w-full shadow-xl">
            <div class="card-body">
                <h2 class="text-center font-extrabold mb-3">Forgot your password?</h2>
                <p class="text-center">Don't worry! Reset your password in few clicks</p>
                <form @submit.prevent="handleForgotPassword">
                    <div class="form-control w-full">
                        <label class="label">
                            <span class="label-text">Email</span>
                        </label>
                        <input type="email" placeholder="john@example.com" autocomplete="email"
                            class="input input-bordered w-full" v-model="email" />
                    </div>
                    <div class="text-center">
                        <button type="submit" class="btn variant-filled mt-4 w-full" :class="submitting ? 'loading' : ''"
                            :disabled="submitting">
                            Continue </button>
                    </div>
                </form>
                <p class="text-center mt-2">
                    <RouterLink to="/login">Back to login ></RouterLink>
                </p>
            </div>
        </div>
    </AuthLayout>
</template>
<script setup lang="ts">
import AuthLayout from '@/layouts/AuthLayout.vue'
import { ref } from 'vue';


const email = ref('')
const submitting = ref(false)


const handleForgotPassword = () => {

}
</script>
